// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeliveryFee   int64                  `protobuf:"varint,1,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	ItemsIn       []*ItemsIn             `protobuf:"bytes,2,rep,name=items_in,json=itemsIn,proto3" json:"items_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderIn) Reset() {
	*x = OrderIn{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderIn) ProtoMessage() {}

func (x *OrderIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderIn.ProtoReflect.Descriptor instead.
func (*OrderIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderIn) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *OrderIn) GetItemsIn() []*ItemsIn {
	if x != nil {
		return x.ItemsIn
	}
	return nil
}

type ItemsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ItemsIn) Reset() {
	*x = ItemsIn{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ItemsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ItemsIn) ProtoMessage() {}

func (x *ItemsIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ItemsIn.ProtoReflect.Descriptor instead.
func (*ItemsIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *ItemsIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ItemsIn) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Order         *OrderIn               `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetOrder() *OrderIn {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversRequest) Reset() {
	*x = GetDriversRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversRequest) ProtoMessage() {}

func (x *GetDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversRequest.ProtoReflect.Descriptor instead.
func (*GetDriversRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriversRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ChooseDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverRequest) Reset() {
	*x = ChooseDriverRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverRequest) ProtoMessage() {}

func (x *ChooseDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverRequest.ProtoReflect.Descriptor instead.
func (*ChooseDriverRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *ChooseDriverRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ChooseDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GiveRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating        int64                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingRequest) Reset() {
	*x = GiveRatingRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingRequest) ProtoMessage() {}

func (x *GiveRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingRequest.ProtoReflect.Descriptor instead.
func (*GiveRatingRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *GiveRatingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GiveRatingRequest) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DriverApplyForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderRequest) Reset() {
	*x = DriverApplyForOrderRequest{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderRequest) ProtoMessage() {}

func (x *DriverApplyForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *DriverApplyForOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverApplyForOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type DriverCompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderRequest) Reset() {
	*x = DriverCompleteOrderRequest{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderRequest) ProtoMessage() {}

func (x *DriverCompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *DriverCompleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverCompleteOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type Restaurant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*Item                `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Restaurant) Reset() {
	*x = Restaurant{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Restaurant) ProtoMessage() {}

func (x *Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Restaurant.ProtoReflect.Descriptor instead.
func (*Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Restaurant) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*Restaurant          `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                 `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                 `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                  `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                  `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                 `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *CreateOrderResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *CreateOrderResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *CreateOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CreateOrderResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *CreateOrderResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *CreateOrderResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type GetDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*Driver              `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse) Reset() {
	*x = GetDriversResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse) ProtoMessage() {}

func (x *GetDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse.ProtoReflect.Descriptor instead.
func (*GetDriversResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type ChooseDriverResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*Restaurant          `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                 `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                 `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Driver              *Driver                `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	DeliveryFee         int64                  `protobuf:"varint,7,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                  `protobuf:"varint,8,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                 `protobuf:"bytes,9,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChooseDriverResponse) Reset() {
	*x = ChooseDriverResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse) ProtoMessage() {}

func (x *ChooseDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *ChooseDriverResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *ChooseDriverResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *ChooseDriverResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ChooseDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bike          string                 `protobuf:"bytes,4,opt,name=bike,proto3" json:"bike,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Driver) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Driver) GetBike() string {
	if x != nil {
		return x.Bike
	}
	return ""
}

func (x *Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *Driver) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type GiveRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingResponse) Reset() {
	*x = GiveRatingResponse{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingResponse) ProtoMessage() {}

func (x *GiveRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingResponse.ProtoReflect.Descriptor instead.
func (*GiveRatingResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

type DriverGetPendingOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse) Reset() {
	*x = DriverGetPendingOrdersResponse{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *DriverGetPendingOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type Order struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*Restaurant          `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                 `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                 `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                 `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                  `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                  `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                 `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	Driver              *Driver                `protobuf:"bytes,9,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Order) GetRestaurants() []*Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *Order) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *Order) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *Order) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *Order) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *Order) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

func (x *Order) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type DriverApplyForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderResponse) Reset() {
	*x = DriverApplyForOrderResponse{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderResponse) ProtoMessage() {}

func (x *DriverApplyForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

type DriverCompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderResponse) Reset() {
	*x = DriverCompleteOrderResponse{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderResponse) ProtoMessage() {}

func (x *DriverCompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

type PaymentGatewayItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	NetUnitAmount int64                  `protobuf:"varint,6,opt,name=net_unit_amount,json=netUnitAmount,proto3" json:"net_unit_amount,omitempty"`
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentGatewayItem) Reset() {
	*x = PaymentGatewayItem{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentGatewayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentGatewayItem) ProtoMessage() {}

func (x *PaymentGatewayItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentGatewayItem.ProtoReflect.Descriptor instead.
func (*PaymentGatewayItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *PaymentGatewayItem) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PaymentGatewayItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentGatewayItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentGatewayItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentGatewayItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PaymentGatewayItem) GetNetUnitAmount() int64 {
	if x != nil {
		return x.NetUnitAmount
	}
	return 0
}

func (x *PaymentGatewayItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PaymentGatewayItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreatePaymentSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentType   string                 `protobuf:"bytes,1,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Items         []*PaymentGatewayItem  `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentSessionRequest) Reset() {
	*x = CreatePaymentSessionRequest{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionRequest) ProtoMessage() {}

func (x *CreatePaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *CreatePaymentSessionRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentSessionRequest) GetItems() []*PaymentGatewayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePaymentSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Created          string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated          string                 `protobuf:"bytes,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ReferenceId      string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Currency         string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount           int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Country          string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	ExpiresAt        string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SessionType      string                 `protobuf:"bytes,10,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	Mode             string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`
	Locale           string                 `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	BusinessId       string                 `protobuf:"bytes,13,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CustomerId       string                 `protobuf:"bytes,14,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CaptureMethod    string                 `protobuf:"bytes,15,opt,name=capture_method,json=captureMethod,proto3" json:"capture_method,omitempty"`
	Description      string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	Items            []*PaymentGatewayItem  `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	SuccessReturnUrl string                 `protobuf:"bytes,18,opt,name=success_return_url,json=successReturnUrl,proto3" json:"success_return_url,omitempty"`
	CancelReturnUrl  string                 `protobuf:"bytes,19,opt,name=cancel_return_url,json=cancelReturnUrl,proto3" json:"cancel_return_url,omitempty"`
	PaymentLinkUrl   string                 `protobuf:"bytes,20,opt,name=payment_link_url,json=paymentLinkUrl,proto3" json:"payment_link_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentSessionResponse) Reset() {
	*x = CreatePaymentSessionResponse{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionResponse) ProtoMessage() {}

func (x *CreatePaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *CreatePaymentSessionResponse) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentSessionResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCaptureMethod() string {
	if x != nil {
		return x.CaptureMethod
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetItems() []*PaymentGatewayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePaymentSessionResponse) GetSuccessReturnUrl() string {
	if x != nil {
		return x.SuccessReturnUrl
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCancelReturnUrl() string {
	if x != nil {
		return x.CancelReturnUrl
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetPaymentLinkUrl() string {
	if x != nil {
		return x.PaymentLinkUrl
	}
	return ""
}

type GetOrdersByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIDRequest) Reset() {
	*x = GetOrdersByUserIDRequest{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDRequest) ProtoMessage() {}

func (x *GetOrdersByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

func (x *GetOrdersByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetOrdersByUserIDRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type GetOrdersByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrdersByUserIDResponse) Reset() {
	*x = GetOrdersByUserIDResponse{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrdersByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrdersByUserIDResponse) ProtoMessage() {}

func (x *GetOrdersByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrdersByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetOrdersByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{23}
}

func (x *GetOrdersByUserIDResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\border_pb\x1a\x1bgoogle/protobuf/empty.proto\"Z\n" +
	"\aOrderIn\x12!\n" +
	"\fdelivery_fee\x18\x01 \x01(\x03R\vdeliveryFee\x12,\n" +
	"\bitems_in\x18\x02 \x03(\v2\x11.order_pb.ItemsInR\aitemsIn\"5\n" +
	"\aItemsIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\"u\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x12'\n" +
	"\x05order\x18\x03 \x01(\v2\x11.order_pb.OrderInR\x05order\".\n" +
	"\x11GetDriversRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"M\n" +
	"\x13ChooseDriverRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"F\n" +
	"\x11GiveRatingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x03R\x06rating\"T\n" +
	"\x1aDriverApplyForOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"T\n" +
	"\x1aDriverCompleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"p\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12$\n" +
	"\x05items\x18\x04 \x03(\v2\x0e.order_pb.ItemR\x05items\"\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xc2\x02\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\vrestaurants\x18\x02 \x03(\v2\x14.order_pb.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\"@\n" +
	"\x12GetDriversResponse\x12*\n" +
	"\adrivers\x18\x01 \x03(\v2\x10.order_pb.DriverR\adrivers\"\xed\x02\n" +
	"\x14ChooseDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\vrestaurants\x18\x02 \x03(\v2\x14.order_pb.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12(\n" +
	"\x06driver\x18\x06 \x01(\v2\x10.order_pb.DriverR\x06driver\x12!\n" +
	"\fdelivery_fee\x18\a \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\b \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\t \x01(\tR\vpaymentLink\"\xaf\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04bike\x18\x04 \x01(\tR\x04bike\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\"\x14\n" +
	"\x12GiveRatingResponse\"I\n" +
	"\x1eDriverGetPendingOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order_pb.OrderR\x06orders\"\xde\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x126\n" +
	"\vrestaurants\x18\x02 \x03(\v2\x14.order_pb.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\x12(\n" +
	"\x06driver\x18\t \x01(\v2\x10.order_pb.DriverR\x06driver\"\x1d\n" +
	"\x1bDriverApplyForOrderResponse\"\x1d\n" +
	"\x1bDriverCompleteOrderResponse\"\xf3\x01\n" +
	"\x12PaymentGatewayItem\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12&\n" +
	"\x0fnet_unit_amount\x18\x06 \x01(\x03R\rnetUnitAmount\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\xc4\x01\n" +
	"\x1bCreatePaymentSessionRequest\x12!\n" +
	"\fpayment_type\x18\x01 \x01(\tR\vpaymentType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x122\n" +
	"\x05items\x18\x05 \x03(\v2\x1c.order_pb.PaymentGatewayItemR\x05items\"\xba\x05\n" +
	"\x1cCreatePaymentSessionResponse\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\tR\aupdated\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12!\n" +
	"\fsession_type\x18\n" +
	" \x01(\tR\vsessionType\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12\x1f\n" +
	"\vbusiness_id\x18\r \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vcustomer_id\x18\x0e \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0ecapture_method\x18\x0f \x01(\tR\rcaptureMethod\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x122\n" +
	"\x05items\x18\x11 \x03(\v2\x1c.order_pb.PaymentGatewayItemR\x05items\x12,\n" +
	"\x12success_return_url\x18\x12 \x01(\tR\x10successReturnUrl\x12*\n" +
	"\x11cancel_return_url\x18\x13 \x01(\tR\x0fcancelReturnUrl\x12(\n" +
	"\x10payment_link_url\x18\x14 \x01(\tR\x0epaymentLinkUrl\"G\n" +
	"\x18GetOrdersByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"D\n" +
	"\x19GetOrdersByUserIDResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order_pb.OrderR\x06orders2\xa4\x06\n" +
	"\fOrderService\x12J\n" +
	"\vCreateOrder\x12\x1c.order_pb.CreateOrderRequest\x1a\x1d.order_pb.CreateOrderResponse\x12G\n" +
	"\n" +
	"GetDrivers\x12\x1b.order_pb.GetDriversRequest\x1a\x1c.order_pb.GetDriversResponse\x12M\n" +
	"\fChooseDriver\x12\x1d.order_pb.ChooseDriverRequest\x1a\x1e.order_pb.ChooseDriverResponse\x12G\n" +
	"\n" +
	"GiveRating\x12\x1b.order_pb.GiveRatingRequest\x1a\x1c.order_pb.GiveRatingResponse\x12Z\n" +
	"\x16DriverGetPendingOrders\x12\x16.google.protobuf.Empty\x1a(.order_pb.DriverGetPendingOrdersResponse\x12b\n" +
	"\x13DriverApplyForOrder\x12$.order_pb.DriverApplyForOrderRequest\x1a%.order_pb.DriverApplyForOrderResponse\x12b\n" +
	"\x13DriverCompleteOrder\x12$.order_pb.DriverCompleteOrderRequest\x1a%.order_pb.DriverCompleteOrderResponse\x12e\n" +
	"\x14CreatePaymentSession\x12%.order_pb.CreatePaymentSessionRequest\x1a&.order_pb.CreatePaymentSessionResponse\x12\\\n" +
	"\x11GetOrdersByUserID\x12\".order_pb.GetOrdersByUserIDRequest\x1a#.order_pb.GetOrdersByUserIDResponseB5Z3github.com/airlangga-hub/food-delivery-app/order/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_order_proto_goTypes = []any{
	(*OrderIn)(nil),                        // 0: order_pb.OrderIn
	(*ItemsIn)(nil),                        // 1: order_pb.ItemsIn
	(*CreateOrderRequest)(nil),             // 2: order_pb.CreateOrderRequest
	(*GetDriversRequest)(nil),              // 3: order_pb.GetDriversRequest
	(*ChooseDriverRequest)(nil),            // 4: order_pb.ChooseDriverRequest
	(*GiveRatingRequest)(nil),              // 5: order_pb.GiveRatingRequest
	(*DriverApplyForOrderRequest)(nil),     // 6: order_pb.DriverApplyForOrderRequest
	(*DriverCompleteOrderRequest)(nil),     // 7: order_pb.DriverCompleteOrderRequest
	(*Restaurant)(nil),                     // 8: order_pb.Restaurant
	(*Item)(nil),                           // 9: order_pb.Item
	(*CreateOrderResponse)(nil),            // 10: order_pb.CreateOrderResponse
	(*GetDriversResponse)(nil),             // 11: order_pb.GetDriversResponse
	(*ChooseDriverResponse)(nil),           // 12: order_pb.ChooseDriverResponse
	(*Driver)(nil),                         // 13: order_pb.Driver
	(*GiveRatingResponse)(nil),             // 14: order_pb.GiveRatingResponse
	(*DriverGetPendingOrdersResponse)(nil), // 15: order_pb.DriverGetPendingOrdersResponse
	(*Order)(nil),                          // 16: order_pb.Order
	(*DriverApplyForOrderResponse)(nil),    // 17: order_pb.DriverApplyForOrderResponse
	(*DriverCompleteOrderResponse)(nil),    // 18: order_pb.DriverCompleteOrderResponse
	(*PaymentGatewayItem)(nil),             // 19: order_pb.PaymentGatewayItem
	(*CreatePaymentSessionRequest)(nil),    // 20: order_pb.CreatePaymentSessionRequest
	(*CreatePaymentSessionResponse)(nil),   // 21: order_pb.CreatePaymentSessionResponse
	(*GetOrdersByUserIDRequest)(nil),       // 22: order_pb.GetOrdersByUserIDRequest
	(*GetOrdersByUserIDResponse)(nil),      // 23: order_pb.GetOrdersByUserIDResponse
	(*emptypb.Empty)(nil),                  // 24: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	1,  // 0: order_pb.OrderIn.items_in:type_name -> order_pb.ItemsIn
	0,  // 1: order_pb.CreateOrderRequest.order:type_name -> order_pb.OrderIn
	9,  // 2: order_pb.Restaurant.items:type_name -> order_pb.Item
	8,  // 3: order_pb.CreateOrderResponse.restaurants:type_name -> order_pb.Restaurant
	13, // 4: order_pb.GetDriversResponse.drivers:type_name -> order_pb.Driver
	8,  // 5: order_pb.ChooseDriverResponse.restaurants:type_name -> order_pb.Restaurant
	13, // 6: order_pb.ChooseDriverResponse.driver:type_name -> order_pb.Driver
	16, // 7: order_pb.DriverGetPendingOrdersResponse.orders:type_name -> order_pb.Order
	8,  // 8: order_pb.Order.restaurants:type_name -> order_pb.Restaurant
	13, // 9: order_pb.Order.driver:type_name -> order_pb.Driver
	19, // 10: order_pb.CreatePaymentSessionRequest.items:type_name -> order_pb.PaymentGatewayItem
	19, // 11: order_pb.CreatePaymentSessionResponse.items:type_name -> order_pb.PaymentGatewayItem
	16, // 12: order_pb.GetOrdersByUserIDResponse.orders:type_name -> order_pb.Order
	2,  // 13: order_pb.OrderService.CreateOrder:input_type -> order_pb.CreateOrderRequest
	3,  // 14: order_pb.OrderService.GetDrivers:input_type -> order_pb.GetDriversRequest
	4,  // 15: order_pb.OrderService.ChooseDriver:input_type -> order_pb.ChooseDriverRequest
	5,  // 16: order_pb.OrderService.GiveRating:input_type -> order_pb.GiveRatingRequest
	24, // 17: order_pb.OrderService.DriverGetPendingOrders:input_type -> google.protobuf.Empty
	6,  // 18: order_pb.OrderService.DriverApplyForOrder:input_type -> order_pb.DriverApplyForOrderRequest
	7,  // 19: order_pb.OrderService.DriverCompleteOrder:input_type -> order_pb.DriverCompleteOrderRequest
	20, // 20: order_pb.OrderService.CreatePaymentSession:input_type -> order_pb.CreatePaymentSessionRequest
	22, // 21: order_pb.OrderService.GetOrdersByUserID:input_type -> order_pb.GetOrdersByUserIDRequest
	10, // 22: order_pb.OrderService.CreateOrder:output_type -> order_pb.CreateOrderResponse
	11, // 23: order_pb.OrderService.GetDrivers:output_type -> order_pb.GetDriversResponse
	12, // 24: order_pb.OrderService.ChooseDriver:output_type -> order_pb.ChooseDriverResponse
	14, // 25: order_pb.OrderService.GiveRating:output_type -> order_pb.GiveRatingResponse
	15, // 26: order_pb.OrderService.DriverGetPendingOrders:output_type -> order_pb.DriverGetPendingOrdersResponse
	17, // 27: order_pb.OrderService.DriverApplyForOrder:output_type -> order_pb.DriverApplyForOrderResponse
	18, // 28: order_pb.OrderService.DriverCompleteOrder:output_type -> order_pb.DriverCompleteOrderResponse
	21, // 29: order_pb.OrderService.CreatePaymentSession:output_type -> order_pb.CreatePaymentSessionResponse
	23, // 30: order_pb.OrderService.GetOrdersByUserID:output_type -> order_pb.GetOrdersByUserIDResponse
	22, // [22:31] is the sub-list for method output_type
	13, // [13:22] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
