// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: order.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OrderService_CreateOrder_FullMethodName            = "/pb.OrderService/CreateOrder"
	OrderService_GetDrivers_FullMethodName             = "/pb.OrderService/GetDrivers"
	OrderService_ChooseDriver_FullMethodName           = "/pb.OrderService/ChooseDriver"
	OrderService_GiveRating_FullMethodName             = "/pb.OrderService/GiveRating"
	OrderService_DriverGetPendingOrders_FullMethodName = "/pb.OrderService/DriverGetPendingOrders"
	OrderService_DriverApplyForOrder_FullMethodName    = "/pb.OrderService/DriverApplyForOrder"
	OrderService_DriverCompleteOrder_FullMethodName    = "/pb.OrderService/DriverCompleteOrder"
)

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	GetDrivers(ctx context.Context, in *GetDriversRequest, opts ...grpc.CallOption) (*GetDriversResponse, error)
	ChooseDriver(ctx context.Context, in *ChooseDriverRequest, opts ...grpc.CallOption) (*ChooseDriverResponse, error)
	GiveRating(ctx context.Context, in *GiveRatingRequest, opts ...grpc.CallOption) (*GiveRatingResponse, error)
	DriverGetPendingOrders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DriverGetPendingOrdersResponse, error)
	DriverApplyForOrder(ctx context.Context, in *DriverApplyForOrderRequest, opts ...grpc.CallOption) (*DriverApplyForOrderResponse, error)
	DriverCompleteOrder(ctx context.Context, in *DriverCompleteOrderRequest, opts ...grpc.CallOption) (*DriverCompleteOrderResponse, error)
}

type orderServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderServiceClient(cc grpc.ClientConnInterface) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GetDrivers(ctx context.Context, in *GetDriversRequest, opts ...grpc.CallOption) (*GetDriversResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriversResponse)
	err := c.cc.Invoke(ctx, OrderService_GetDrivers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) ChooseDriver(ctx context.Context, in *ChooseDriverRequest, opts ...grpc.CallOption) (*ChooseDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChooseDriverResponse)
	err := c.cc.Invoke(ctx, OrderService_ChooseDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) GiveRating(ctx context.Context, in *GiveRatingRequest, opts ...grpc.CallOption) (*GiveRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GiveRatingResponse)
	err := c.cc.Invoke(ctx, OrderService_GiveRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DriverGetPendingOrders(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*DriverGetPendingOrdersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverGetPendingOrdersResponse)
	err := c.cc.Invoke(ctx, OrderService_DriverGetPendingOrders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DriverApplyForOrder(ctx context.Context, in *DriverApplyForOrderRequest, opts ...grpc.CallOption) (*DriverApplyForOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverApplyForOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_DriverApplyForOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *orderServiceClient) DriverCompleteOrder(ctx context.Context, in *DriverCompleteOrderRequest, opts ...grpc.CallOption) (*DriverCompleteOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DriverCompleteOrderResponse)
	err := c.cc.Invoke(ctx, OrderService_DriverCompleteOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
// All implementations must embed UnimplementedOrderServiceServer
// for forward compatibility.
type OrderServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	GetDrivers(context.Context, *GetDriversRequest) (*GetDriversResponse, error)
	ChooseDriver(context.Context, *ChooseDriverRequest) (*ChooseDriverResponse, error)
	GiveRating(context.Context, *GiveRatingRequest) (*GiveRatingResponse, error)
	DriverGetPendingOrders(context.Context, *emptypb.Empty) (*DriverGetPendingOrdersResponse, error)
	DriverApplyForOrder(context.Context, *DriverApplyForOrderRequest) (*DriverApplyForOrderResponse, error)
	DriverCompleteOrder(context.Context, *DriverCompleteOrderRequest) (*DriverCompleteOrderResponse, error)
	mustEmbedUnimplementedOrderServiceServer()
}

// UnimplementedOrderServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOrderServiceServer struct{}

func (UnimplementedOrderServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedOrderServiceServer) GetDrivers(context.Context, *GetDriversRequest) (*GetDriversResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDrivers not implemented")
}
func (UnimplementedOrderServiceServer) ChooseDriver(context.Context, *ChooseDriverRequest) (*ChooseDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ChooseDriver not implemented")
}
func (UnimplementedOrderServiceServer) GiveRating(context.Context, *GiveRatingRequest) (*GiveRatingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GiveRating not implemented")
}
func (UnimplementedOrderServiceServer) DriverGetPendingOrders(context.Context, *emptypb.Empty) (*DriverGetPendingOrdersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverGetPendingOrders not implemented")
}
func (UnimplementedOrderServiceServer) DriverApplyForOrder(context.Context, *DriverApplyForOrderRequest) (*DriverApplyForOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverApplyForOrder not implemented")
}
func (UnimplementedOrderServiceServer) DriverCompleteOrder(context.Context, *DriverCompleteOrderRequest) (*DriverCompleteOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DriverCompleteOrder not implemented")
}
func (UnimplementedOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {}
func (UnimplementedOrderServiceServer) testEmbeddedByValue()                      {}

// UnsafeOrderServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderServiceServer will
// result in compilation errors.
type UnsafeOrderServiceServer interface {
	mustEmbedUnimplementedOrderServiceServer()
}

func RegisterOrderServiceServer(s grpc.ServiceRegistrar, srv OrderServiceServer) {
	// If the following call panics, it indicates UnimplementedOrderServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OrderService_ServiceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GetDrivers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriversRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GetDrivers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GetDrivers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GetDrivers(ctx, req.(*GetDriversRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_ChooseDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChooseDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).ChooseDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_ChooseDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).ChooseDriver(ctx, req.(*ChooseDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_GiveRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GiveRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).GiveRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_GiveRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).GiveRating(ctx, req.(*GiveRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DriverGetPendingOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DriverGetPendingOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_DriverGetPendingOrders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DriverGetPendingOrders(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DriverApplyForOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverApplyForOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DriverApplyForOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_DriverApplyForOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DriverApplyForOrder(ctx, req.(*DriverApplyForOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OrderService_DriverCompleteOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverCompleteOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).DriverCompleteOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OrderService_DriverCompleteOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).DriverCompleteOrder(ctx, req.(*DriverCompleteOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderService_ServiceDesc is the grpc.ServiceDesc for OrderService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
		{
			MethodName: "GetDrivers",
			Handler:    _OrderService_GetDrivers_Handler,
		},
		{
			MethodName: "ChooseDriver",
			Handler:    _OrderService_ChooseDriver_Handler,
		},
		{
			MethodName: "GiveRating",
			Handler:    _OrderService_GiveRating_Handler,
		},
		{
			MethodName: "DriverGetPendingOrders",
			Handler:    _OrderService_DriverGetPendingOrders_Handler,
		},
		{
			MethodName: "DriverApplyForOrder",
			Handler:    _OrderService_DriverApplyForOrder_Handler,
		},
		{
			MethodName: "DriverCompleteOrder",
			Handler:    _OrderService_DriverCompleteOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
