// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	UserId        string                      `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                      `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Order         *CreateOrderRequest_OrderIn `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CreateOrderRequest) GetOrder() *CreateOrderRequest_OrderIn {
	if x != nil {
		return x.Order
	}
	return nil
}

type GetDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversRequest) Reset() {
	*x = GetDriversRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversRequest) ProtoMessage() {}

func (x *GetDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversRequest.ProtoReflect.Descriptor instead.
func (*GetDriversRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriversRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ChooseDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverRequest) Reset() {
	*x = ChooseDriverRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverRequest) ProtoMessage() {}

func (x *ChooseDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverRequest.ProtoReflect.Descriptor instead.
func (*ChooseDriverRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *ChooseDriverRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ChooseDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GiveRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating        int64                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingRequest) Reset() {
	*x = GiveRatingRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingRequest) ProtoMessage() {}

func (x *GiveRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingRequest.ProtoReflect.Descriptor instead.
func (*GiveRatingRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GiveRatingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GiveRatingRequest) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DriverApplyForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderRequest) Reset() {
	*x = DriverApplyForOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderRequest) ProtoMessage() {}

func (x *DriverApplyForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *DriverApplyForOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverApplyForOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type DriverCompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderRequest) Reset() {
	*x = DriverCompleteOrderRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderRequest) ProtoMessage() {}

func (x *DriverCompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *DriverCompleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverCompleteOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CreateOrderResponse struct {
	state               protoimpl.MessageState            `protogen:"open.v1"`
	Id                  string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*CreateOrderResponse_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                            `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                            `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                            `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                             `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                             `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                            `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse) GetRestaurants() []*CreateOrderResponse_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *CreateOrderResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *CreateOrderResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *CreateOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CreateOrderResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *CreateOrderResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *CreateOrderResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type GetDriversResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Drivers       []*GetDriversResponse_Driver `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse) Reset() {
	*x = GetDriversResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse) ProtoMessage() {}

func (x *GetDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse.ProtoReflect.Descriptor instead.
func (*GetDriversResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriversResponse) GetDrivers() []*GetDriversResponse_Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type ChooseDriverResponse struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	Id                  string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*ChooseDriverResponse_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                             `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                             `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                             `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Driver              *ChooseDriverResponse_Driver       `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	DeliveryFee         int64                              `protobuf:"varint,7,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                              `protobuf:"varint,8,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                             `protobuf:"bytes,9,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChooseDriverResponse) Reset() {
	*x = ChooseDriverResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse) ProtoMessage() {}

func (x *ChooseDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ChooseDriverResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse) GetRestaurants() []*ChooseDriverResponse_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *ChooseDriverResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *ChooseDriverResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ChooseDriverResponse) GetDriver() *ChooseDriverResponse_Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type GiveRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingResponse) Reset() {
	*x = GiveRatingResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingResponse) ProtoMessage() {}

func (x *GiveRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingResponse.ProtoReflect.Descriptor instead.
func (*GiveRatingResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

type DriverGetPendingOrdersResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Orders        []*DriverGetPendingOrdersResponse_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse) Reset() {
	*x = DriverGetPendingOrdersResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *DriverGetPendingOrdersResponse) GetOrders() []*DriverGetPendingOrdersResponse_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type DriverApplyForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderResponse) Reset() {
	*x = DriverApplyForOrderResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderResponse) ProtoMessage() {}

func (x *DriverApplyForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

type DriverCompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderResponse) Reset() {
	*x = DriverCompleteOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderResponse) ProtoMessage() {}

func (x *DriverCompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

type PaymentGatewayItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	NetUnitAmount int64                  `protobuf:"varint,6,opt,name=net_unit_amount,json=netUnitAmount,proto3" json:"net_unit_amount,omitempty"`
	Quantity      int64                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Url           string                 `protobuf:"bytes,8,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PaymentGatewayItem) Reset() {
	*x = PaymentGatewayItem{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentGatewayItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentGatewayItem) ProtoMessage() {}

func (x *PaymentGatewayItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentGatewayItem.ProtoReflect.Descriptor instead.
func (*PaymentGatewayItem) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *PaymentGatewayItem) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *PaymentGatewayItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PaymentGatewayItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PaymentGatewayItem) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *PaymentGatewayItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PaymentGatewayItem) GetNetUnitAmount() int64 {
	if x != nil {
		return x.NetUnitAmount
	}
	return 0
}

func (x *PaymentGatewayItem) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *PaymentGatewayItem) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type CreatePaymentSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentType   string                 `protobuf:"bytes,1,opt,name=payment_type,json=paymentType,proto3" json:"payment_type,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,3,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Items         []*PaymentGatewayItem  `protobuf:"bytes,5,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePaymentSessionRequest) Reset() {
	*x = CreatePaymentSessionRequest{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionRequest) ProtoMessage() {}

func (x *CreatePaymentSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionRequest.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *CreatePaymentSessionRequest) GetPaymentType() string {
	if x != nil {
		return x.PaymentType
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

func (x *CreatePaymentSessionRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentSessionRequest) GetItems() []*PaymentGatewayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreatePaymentSessionResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PaymentSessionId string                 `protobuf:"bytes,1,opt,name=payment_session_id,json=paymentSessionId,proto3" json:"payment_session_id,omitempty"`
	Created          string                 `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	Updated          string                 `protobuf:"bytes,3,opt,name=updated,proto3" json:"updated,omitempty"`
	Status           string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ReferenceId      string                 `protobuf:"bytes,5,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Currency         string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount           int64                  `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Country          string                 `protobuf:"bytes,8,opt,name=country,proto3" json:"country,omitempty"`
	ExpiresAt        string                 `protobuf:"bytes,9,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	SessionType      string                 `protobuf:"bytes,10,opt,name=session_type,json=sessionType,proto3" json:"session_type,omitempty"`
	Mode             string                 `protobuf:"bytes,11,opt,name=mode,proto3" json:"mode,omitempty"`
	Locale           string                 `protobuf:"bytes,12,opt,name=locale,proto3" json:"locale,omitempty"`
	BusinessId       string                 `protobuf:"bytes,13,opt,name=business_id,json=businessId,proto3" json:"business_id,omitempty"`
	CustomerId       string                 `protobuf:"bytes,14,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CaptureMethod    string                 `protobuf:"bytes,15,opt,name=capture_method,json=captureMethod,proto3" json:"capture_method,omitempty"`
	Description      string                 `protobuf:"bytes,16,opt,name=description,proto3" json:"description,omitempty"`
	Items            []*PaymentGatewayItem  `protobuf:"bytes,17,rep,name=items,proto3" json:"items,omitempty"`
	SuccessReturnUrl string                 `protobuf:"bytes,18,opt,name=success_return_url,json=successReturnUrl,proto3" json:"success_return_url,omitempty"`
	CancelReturnUrl  string                 `protobuf:"bytes,19,opt,name=cancel_return_url,json=cancelReturnUrl,proto3" json:"cancel_return_url,omitempty"`
	PaymentLinkUrl   string                 `protobuf:"bytes,20,opt,name=payment_link_url,json=paymentLinkUrl,proto3" json:"payment_link_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreatePaymentSessionResponse) Reset() {
	*x = CreatePaymentSessionResponse{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePaymentSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePaymentSessionResponse) ProtoMessage() {}

func (x *CreatePaymentSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePaymentSessionResponse.ProtoReflect.Descriptor instead.
func (*CreatePaymentSessionResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePaymentSessionResponse) GetPaymentSessionId() string {
	if x != nil {
		return x.PaymentSessionId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCreated() string {
	if x != nil {
		return x.Created
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetUpdated() string {
	if x != nil {
		return x.Updated
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreatePaymentSessionResponse) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetSessionType() string {
	if x != nil {
		return x.SessionType
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetBusinessId() string {
	if x != nil {
		return x.BusinessId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCaptureMethod() string {
	if x != nil {
		return x.CaptureMethod
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetItems() []*PaymentGatewayItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *CreatePaymentSessionResponse) GetSuccessReturnUrl() string {
	if x != nil {
		return x.SuccessReturnUrl
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetCancelReturnUrl() string {
	if x != nil {
		return x.CancelReturnUrl
	}
	return ""
}

func (x *CreatePaymentSessionResponse) GetPaymentLinkUrl() string {
	if x != nil {
		return x.PaymentLinkUrl
	}
	return ""
}

type CreateOrderRequest_OrderIn struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	DeliveryFee   int64                                 `protobuf:"varint,1,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	ItemsIn       []*CreateOrderRequest_OrderIn_ItemsIn `protobuf:"bytes,2,rep,name=items_in,json=itemsIn,proto3" json:"items_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderIn) Reset() {
	*x = CreateOrderRequest_OrderIn{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderIn) ProtoMessage() {}

func (x *CreateOrderRequest_OrderIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderIn.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateOrderRequest_OrderIn) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *CreateOrderRequest_OrderIn) GetItemsIn() []*CreateOrderRequest_OrderIn_ItemsIn {
	if x != nil {
		return x.ItemsIn
	}
	return nil
}

type CreateOrderRequest_OrderIn_ItemsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) Reset() {
	*x = CreateOrderRequest_OrderIn_ItemsIn{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderIn_ItemsIn) ProtoMessage() {}

func (x *CreateOrderRequest_OrderIn_ItemsIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderIn_ItemsIn.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderIn_ItemsIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse_Restaurant struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*CreateOrderResponse_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse_Restaurant) Reset() {
	*x = CreateOrderResponse_Restaurant{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse_Restaurant) ProtoMessage() {}

func (x *CreateOrderResponse_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse_Restaurant.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreateOrderResponse_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetItems() []*CreateOrderResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse_Item) Reset() {
	*x = CreateOrderResponse_Item{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse_Item) ProtoMessage() {}

func (x *CreateOrderResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse_Item.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CreateOrderResponse_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderResponse_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderResponse_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetDriversResponse_Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bike          string                 `protobuf:"bytes,4,opt,name=bike,proto3" json:"bike,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse_Driver) Reset() {
	*x = GetDriversResponse_Driver{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse_Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse_Driver) ProtoMessage() {}

func (x *GetDriversResponse_Driver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse_Driver.ProtoReflect.Descriptor instead.
func (*GetDriversResponse_Driver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetDriversResponse_Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *GetDriversResponse_Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetBike() string {
	if x != nil {
		return x.Bike
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type ChooseDriverResponse_Restaurant struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*ChooseDriverResponse_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Restaurant) Reset() {
	*x = ChooseDriverResponse_Restaurant{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Restaurant) ProtoMessage() {}

func (x *ChooseDriverResponse_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Restaurant.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ChooseDriverResponse_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetItems() []*ChooseDriverResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChooseDriverResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Item) Reset() {
	*x = ChooseDriverResponse_Item{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Item) ProtoMessage() {}

func (x *ChooseDriverResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Item.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 1}
}

func (x *ChooseDriverResponse_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ChooseDriverResponse_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ChooseDriverResponse_Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bike          string                 `protobuf:"bytes,4,opt,name=bike,proto3" json:"bike,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Driver) Reset() {
	*x = ChooseDriverResponse_Driver{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Driver) ProtoMessage() {}

func (x *ChooseDriverResponse_Driver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Driver.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Driver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 2}
}

func (x *ChooseDriverResponse_Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *ChooseDriverResponse_Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetBike() string {
	if x != nil {
		return x.Bike
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type DriverGetPendingOrdersResponse_Order struct {
	state               protoimpl.MessageState                             `protogen:"open.v1"`
	Id                  string                                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*DriverGetPendingOrdersResponse_Order_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                                             `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                                             `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                                             `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                                              `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                                              `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                                             `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order) Reset() {
	*x = DriverGetPendingOrdersResponse_Order{}
	mi := &file_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DriverGetPendingOrdersResponse_Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetRestaurants() []*DriverGetPendingOrdersResponse_Order_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *DriverGetPendingOrdersResponse_Order) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type DriverGetPendingOrdersResponse_Order_Restaurant struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Id            string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                                       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*DriverGetPendingOrdersResponse_Order_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) Reset() {
	*x = DriverGetPendingOrdersResponse_Order_Restaurant{}
	mi := &file_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order_Restaurant) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order_Restaurant.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0, 0}
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetItems() []*DriverGetPendingOrdersResponse_Order_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type DriverGetPendingOrdersResponse_Order_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order_Item) Reset() {
	*x = DriverGetPendingOrdersResponse_Order_Item{}
	mi := &file_order_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order_Item) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order_Item.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0, 1}
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\xab\x02\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x124\n" +
	"\x05order\x18\x03 \x01(\v2\x1e.pb.CreateOrderRequest.OrderInR\x05order\x1a\xa6\x01\n" +
	"\aOrderIn\x12!\n" +
	"\fdelivery_fee\x18\x01 \x01(\x03R\vdeliveryFee\x12A\n" +
	"\bitems_in\x18\x02 \x03(\v2&.pb.CreateOrderRequest.OrderIn.ItemsInR\aitemsIn\x1a5\n" +
	"\aItemsIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\".\n" +
	"\x11GetDriversRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"M\n" +
	"\x13ChooseDriverRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"F\n" +
	"\x11GiveRatingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x03R\x06rating\"T\n" +
	"\x1aDriverApplyForOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"T\n" +
	"\x1aDriverCompleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\xae\x04\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12D\n" +
	"\vrestaurants\x18\x02 \x03(\v2\".pb.CreateOrderResponse.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\x1a~\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.pb.CreateOrderResponse.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xff\x01\n" +
	"\x12GetDriversResponse\x127\n" +
	"\adrivers\x18\x01 \x03(\v2\x1d.pb.GetDriversResponse.DriverR\adrivers\x1a\xaf\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04bike\x18\x04 \x01(\tR\x04bike\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\"\x9c\x06\n" +
	"\x14ChooseDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\vrestaurants\x18\x02 \x03(\v2#.pb.ChooseDriverResponse.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x127\n" +
	"\x06driver\x18\x06 \x01(\v2\x1f.pb.ChooseDriverResponse.DriverR\x06driver\x12!\n" +
	"\fdelivery_fee\x18\a \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\b \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\t \x01(\tR\vpaymentLink\x1a\x7f\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x123\n" +
	"\x05items\x18\x04 \x03(\v2\x1d.pb.ChooseDriverResponse.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x1a\xaf\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04bike\x18\x04 \x01(\tR\x04bike\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\"\x14\n" +
	"\x12GiveRatingResponse\"\xa8\x05\n" +
	"\x1eDriverGetPendingOrdersResponse\x12@\n" +
	"\x06orders\x18\x01 \x03(\v2(.pb.DriverGetPendingOrdersResponse.OrderR\x06orders\x1a\xc3\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12U\n" +
	"\vrestaurants\x18\x02 \x03(\v23.pb.DriverGetPendingOrdersResponse.Order.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\x1a\x8f\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12C\n" +
	"\x05items\x18\x04 \x03(\v2-.pb.DriverGetPendingOrdersResponse.Order.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\x1d\n" +
	"\x1bDriverApplyForOrderResponse\"\x1d\n" +
	"\x1bDriverCompleteOrderResponse\"\xf3\x01\n" +
	"\x12PaymentGatewayItem\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12&\n" +
	"\x0fnet_unit_amount\x18\x06 \x01(\x03R\rnetUnitAmount\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x03R\bquantity\x12\x10\n" +
	"\x03url\x18\b \x01(\tR\x03url\"\xbe\x01\n" +
	"\x1bCreatePaymentSessionRequest\x12!\n" +
	"\fpayment_type\x18\x01 \x01(\tR\vpaymentType\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x03 \x01(\tR\tuserEmail\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12,\n" +
	"\x05items\x18\x05 \x03(\v2\x16.pb.PaymentGatewayItemR\x05items\"\xb4\x05\n" +
	"\x1cCreatePaymentSessionResponse\x12,\n" +
	"\x12payment_session_id\x18\x01 \x01(\tR\x10paymentSessionId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\tR\acreated\x12\x18\n" +
	"\aupdated\x18\x03 \x01(\tR\aupdated\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12!\n" +
	"\freference_id\x18\x05 \x01(\tR\vreferenceId\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\a \x01(\x03R\x06amount\x12\x18\n" +
	"\acountry\x18\b \x01(\tR\acountry\x12\x1d\n" +
	"\n" +
	"expires_at\x18\t \x01(\tR\texpiresAt\x12!\n" +
	"\fsession_type\x18\n" +
	" \x01(\tR\vsessionType\x12\x12\n" +
	"\x04mode\x18\v \x01(\tR\x04mode\x12\x16\n" +
	"\x06locale\x18\f \x01(\tR\x06locale\x12\x1f\n" +
	"\vbusiness_id\x18\r \x01(\tR\n" +
	"businessId\x12\x1f\n" +
	"\vcustomer_id\x18\x0e \x01(\tR\n" +
	"customerId\x12%\n" +
	"\x0ecapture_method\x18\x0f \x01(\tR\rcaptureMethod\x12 \n" +
	"\vdescription\x18\x10 \x01(\tR\vdescription\x12,\n" +
	"\x05items\x18\x11 \x03(\v2\x16.pb.PaymentGatewayItemR\x05items\x12,\n" +
	"\x12success_return_url\x18\x12 \x01(\tR\x10successReturnUrl\x12*\n" +
	"\x11cancel_return_url\x18\x13 \x01(\tR\x0fcancelReturnUrl\x12(\n" +
	"\x10payment_link_url\x18\x14 \x01(\tR\x0epaymentLinkUrl2\xec\x04\n" +
	"\fOrderService\x12>\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x17.pb.CreateOrderResponse\x12;\n" +
	"\n" +
	"GetDrivers\x12\x15.pb.GetDriversRequest\x1a\x16.pb.GetDriversResponse\x12A\n" +
	"\fChooseDriver\x12\x17.pb.ChooseDriverRequest\x1a\x18.pb.ChooseDriverResponse\x12;\n" +
	"\n" +
	"GiveRating\x12\x15.pb.GiveRatingRequest\x1a\x16.pb.GiveRatingResponse\x12T\n" +
	"\x16DriverGetPendingOrders\x12\x16.google.protobuf.Empty\x1a\".pb.DriverGetPendingOrdersResponse\x12V\n" +
	"\x13DriverApplyForOrder\x12\x1e.pb.DriverApplyForOrderRequest\x1a\x1f.pb.DriverApplyForOrderResponse\x12V\n" +
	"\x13DriverCompleteOrder\x12\x1e.pb.DriverCompleteOrderRequest\x1a\x1f.pb.DriverCompleteOrderResponse\x12Y\n" +
	"\x14CreatePaymentSession\x12\x1f.pb.CreatePaymentSessionRequest\x1a .pb.CreatePaymentSessionResponseB5Z3github.com/airlangga-hub/food-delivery-app/order/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),                              // 0: pb.CreateOrderRequest
	(*GetDriversRequest)(nil),                               // 1: pb.GetDriversRequest
	(*ChooseDriverRequest)(nil),                             // 2: pb.ChooseDriverRequest
	(*GiveRatingRequest)(nil),                               // 3: pb.GiveRatingRequest
	(*DriverApplyForOrderRequest)(nil),                      // 4: pb.DriverApplyForOrderRequest
	(*DriverCompleteOrderRequest)(nil),                      // 5: pb.DriverCompleteOrderRequest
	(*CreateOrderResponse)(nil),                             // 6: pb.CreateOrderResponse
	(*GetDriversResponse)(nil),                              // 7: pb.GetDriversResponse
	(*ChooseDriverResponse)(nil),                            // 8: pb.ChooseDriverResponse
	(*GiveRatingResponse)(nil),                              // 9: pb.GiveRatingResponse
	(*DriverGetPendingOrdersResponse)(nil),                  // 10: pb.DriverGetPendingOrdersResponse
	(*DriverApplyForOrderResponse)(nil),                     // 11: pb.DriverApplyForOrderResponse
	(*DriverCompleteOrderResponse)(nil),                     // 12: pb.DriverCompleteOrderResponse
	(*PaymentGatewayItem)(nil),                              // 13: pb.PaymentGatewayItem
	(*CreatePaymentSessionRequest)(nil),                     // 14: pb.CreatePaymentSessionRequest
	(*CreatePaymentSessionResponse)(nil),                    // 15: pb.CreatePaymentSessionResponse
	(*CreateOrderRequest_OrderIn)(nil),                      // 16: pb.CreateOrderRequest.OrderIn
	(*CreateOrderRequest_OrderIn_ItemsIn)(nil),              // 17: pb.CreateOrderRequest.OrderIn.ItemsIn
	(*CreateOrderResponse_Restaurant)(nil),                  // 18: pb.CreateOrderResponse.Restaurant
	(*CreateOrderResponse_Item)(nil),                        // 19: pb.CreateOrderResponse.Item
	(*GetDriversResponse_Driver)(nil),                       // 20: pb.GetDriversResponse.Driver
	(*ChooseDriverResponse_Restaurant)(nil),                 // 21: pb.ChooseDriverResponse.Restaurant
	(*ChooseDriverResponse_Item)(nil),                       // 22: pb.ChooseDriverResponse.Item
	(*ChooseDriverResponse_Driver)(nil),                     // 23: pb.ChooseDriverResponse.Driver
	(*DriverGetPendingOrdersResponse_Order)(nil),            // 24: pb.DriverGetPendingOrdersResponse.Order
	(*DriverGetPendingOrdersResponse_Order_Restaurant)(nil), // 25: pb.DriverGetPendingOrdersResponse.Order.Restaurant
	(*DriverGetPendingOrdersResponse_Order_Item)(nil),       // 26: pb.DriverGetPendingOrdersResponse.Order.Item
	(*emptypb.Empty)(nil),                                   // 27: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	16, // 0: pb.CreateOrderRequest.order:type_name -> pb.CreateOrderRequest.OrderIn
	18, // 1: pb.CreateOrderResponse.restaurants:type_name -> pb.CreateOrderResponse.Restaurant
	20, // 2: pb.GetDriversResponse.drivers:type_name -> pb.GetDriversResponse.Driver
	21, // 3: pb.ChooseDriverResponse.restaurants:type_name -> pb.ChooseDriverResponse.Restaurant
	23, // 4: pb.ChooseDriverResponse.driver:type_name -> pb.ChooseDriverResponse.Driver
	24, // 5: pb.DriverGetPendingOrdersResponse.orders:type_name -> pb.DriverGetPendingOrdersResponse.Order
	13, // 6: pb.CreatePaymentSessionRequest.items:type_name -> pb.PaymentGatewayItem
	13, // 7: pb.CreatePaymentSessionResponse.items:type_name -> pb.PaymentGatewayItem
	17, // 8: pb.CreateOrderRequest.OrderIn.items_in:type_name -> pb.CreateOrderRequest.OrderIn.ItemsIn
	19, // 9: pb.CreateOrderResponse.Restaurant.items:type_name -> pb.CreateOrderResponse.Item
	22, // 10: pb.ChooseDriverResponse.Restaurant.items:type_name -> pb.ChooseDriverResponse.Item
	25, // 11: pb.DriverGetPendingOrdersResponse.Order.restaurants:type_name -> pb.DriverGetPendingOrdersResponse.Order.Restaurant
	26, // 12: pb.DriverGetPendingOrdersResponse.Order.Restaurant.items:type_name -> pb.DriverGetPendingOrdersResponse.Order.Item
	0,  // 13: pb.OrderService.CreateOrder:input_type -> pb.CreateOrderRequest
	1,  // 14: pb.OrderService.GetDrivers:input_type -> pb.GetDriversRequest
	2,  // 15: pb.OrderService.ChooseDriver:input_type -> pb.ChooseDriverRequest
	3,  // 16: pb.OrderService.GiveRating:input_type -> pb.GiveRatingRequest
	27, // 17: pb.OrderService.DriverGetPendingOrders:input_type -> google.protobuf.Empty
	4,  // 18: pb.OrderService.DriverApplyForOrder:input_type -> pb.DriverApplyForOrderRequest
	5,  // 19: pb.OrderService.DriverCompleteOrder:input_type -> pb.DriverCompleteOrderRequest
	14, // 20: pb.OrderService.CreatePaymentSession:input_type -> pb.CreatePaymentSessionRequest
	6,  // 21: pb.OrderService.CreateOrder:output_type -> pb.CreateOrderResponse
	7,  // 22: pb.OrderService.GetDrivers:output_type -> pb.GetDriversResponse
	8,  // 23: pb.OrderService.ChooseDriver:output_type -> pb.ChooseDriverResponse
	9,  // 24: pb.OrderService.GiveRating:output_type -> pb.GiveRatingResponse
	10, // 25: pb.OrderService.DriverGetPendingOrders:output_type -> pb.DriverGetPendingOrdersResponse
	11, // 26: pb.OrderService.DriverApplyForOrder:output_type -> pb.DriverApplyForOrderResponse
	12, // 27: pb.OrderService.DriverCompleteOrder:output_type -> pb.DriverCompleteOrderResponse
	15, // 28: pb.OrderService.CreatePaymentSession:output_type -> pb.CreatePaymentSessionResponse
	21, // [21:29] is the sub-list for method output_type
	13, // [13:21] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
