// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UserEmail     string                 `protobuf:"bytes,2,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateOrderRequest) GetUserEmail() string {
	if x != nil {
		return x.UserEmail
	}
	return ""
}

type GetDriversRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversRequest) Reset() {
	*x = GetDriversRequest{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversRequest) ProtoMessage() {}

func (x *GetDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversRequest.ProtoReflect.Descriptor instead.
func (*GetDriversRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetDriversRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type ChooseDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverRequest) Reset() {
	*x = ChooseDriverRequest{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverRequest) ProtoMessage() {}

func (x *ChooseDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverRequest.ProtoReflect.Descriptor instead.
func (*ChooseDriverRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *ChooseDriverRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ChooseDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GiveRatingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Rating        int64                  `protobuf:"varint,2,opt,name=rating,proto3" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingRequest) Reset() {
	*x = GiveRatingRequest{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingRequest) ProtoMessage() {}

func (x *GiveRatingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingRequest.ProtoReflect.Descriptor instead.
func (*GiveRatingRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GiveRatingRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *GiveRatingRequest) GetRating() int64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

type DriverApplyForOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderRequest) Reset() {
	*x = DriverApplyForOrderRequest{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderRequest) ProtoMessage() {}

func (x *DriverApplyForOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *DriverApplyForOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverApplyForOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type DriverCompleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	DriverId      string                 `protobuf:"bytes,2,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderRequest) Reset() {
	*x = DriverCompleteOrderRequest{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderRequest) ProtoMessage() {}

func (x *DriverCompleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *DriverCompleteOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *DriverCompleteOrderRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CreateOrderResponse struct {
	state               protoimpl.MessageState            `protogen:"open.v1"`
	Id                  string                            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*CreateOrderResponse_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                            `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                            `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                            `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                             `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                             `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                            `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateOrderResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse) GetRestaurants() []*CreateOrderResponse_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *CreateOrderResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *CreateOrderResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *CreateOrderResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *CreateOrderResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *CreateOrderResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *CreateOrderResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type GetDriversResponse struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Drivers       []*GetDriversResponse_Driver `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse) Reset() {
	*x = GetDriversResponse{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse) ProtoMessage() {}

func (x *GetDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse.ProtoReflect.Descriptor instead.
func (*GetDriversResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetDriversResponse) GetDrivers() []*GetDriversResponse_Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type ChooseDriverResponse struct {
	state               protoimpl.MessageState             `protogen:"open.v1"`
	Id                  string                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*ChooseDriverResponse_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                             `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                             `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                             `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	Driver              *ChooseDriverResponse_Driver       `protobuf:"bytes,6,opt,name=driver,proto3" json:"driver,omitempty"`
	DeliveryFee         int64                              `protobuf:"varint,7,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                              `protobuf:"varint,8,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                             `protobuf:"bytes,9,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ChooseDriverResponse) Reset() {
	*x = ChooseDriverResponse{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse) ProtoMessage() {}

func (x *ChooseDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *ChooseDriverResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse) GetRestaurants() []*ChooseDriverResponse_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *ChooseDriverResponse) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *ChooseDriverResponse) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *ChooseDriverResponse) GetDriver() *ChooseDriverResponse_Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

func (x *ChooseDriverResponse) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *ChooseDriverResponse) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type GiveRatingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GiveRatingResponse) Reset() {
	*x = GiveRatingResponse{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GiveRatingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GiveRatingResponse) ProtoMessage() {}

func (x *GiveRatingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GiveRatingResponse.ProtoReflect.Descriptor instead.
func (*GiveRatingResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

type DriverGetPendingOrdersResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	Orders        []*DriverGetPendingOrdersResponse_Order `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse) Reset() {
	*x = DriverGetPendingOrdersResponse{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *DriverGetPendingOrdersResponse) GetOrders() []*DriverGetPendingOrdersResponse_Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

type DriverApplyForOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverApplyForOrderResponse) Reset() {
	*x = DriverApplyForOrderResponse{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverApplyForOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverApplyForOrderResponse) ProtoMessage() {}

func (x *DriverApplyForOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverApplyForOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverApplyForOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

type DriverCompleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverCompleteOrderResponse) Reset() {
	*x = DriverCompleteOrderResponse{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverCompleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverCompleteOrderResponse) ProtoMessage() {}

func (x *DriverCompleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverCompleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DriverCompleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

type CreateOrderRequest_OrderIn struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	DeliveryFee   int64                                 `protobuf:"varint,1,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	ItemsIn       []*CreateOrderRequest_OrderIn_ItemsIn `protobuf:"bytes,2,rep,name=items_in,json=itemsIn,proto3" json:"items_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderIn) Reset() {
	*x = CreateOrderRequest_OrderIn{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderIn) ProtoMessage() {}

func (x *CreateOrderRequest_OrderIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderIn.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0}
}

func (x *CreateOrderRequest_OrderIn) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *CreateOrderRequest_OrderIn) GetItemsIn() []*CreateOrderRequest_OrderIn_ItemsIn {
	if x != nil {
		return x.ItemsIn
	}
	return nil
}

type CreateOrderRequest_OrderIn_ItemsIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Quantity      int64                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) Reset() {
	*x = CreateOrderRequest_OrderIn_ItemsIn{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest_OrderIn_ItemsIn) ProtoMessage() {}

func (x *CreateOrderRequest_OrderIn_ItemsIn) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest_OrderIn_ItemsIn.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest_OrderIn_ItemsIn) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderRequest_OrderIn_ItemsIn) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type CreateOrderResponse_Restaurant struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Id            string                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*CreateOrderResponse_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse_Restaurant) Reset() {
	*x = CreateOrderResponse_Restaurant{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse_Restaurant) ProtoMessage() {}

func (x *CreateOrderResponse_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse_Restaurant.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6, 0}
}

func (x *CreateOrderResponse_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateOrderResponse_Restaurant) GetItems() []*CreateOrderResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateOrderResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse_Item) Reset() {
	*x = CreateOrderResponse_Item{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse_Item) ProtoMessage() {}

func (x *CreateOrderResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse_Item.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6, 1}
}

func (x *CreateOrderResponse_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateOrderResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateOrderResponse_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateOrderResponse_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type GetDriversResponse_Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bike          string                 `protobuf:"bytes,4,opt,name=bike,proto3" json:"bike,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriversResponse_Driver) Reset() {
	*x = GetDriversResponse_Driver{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriversResponse_Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriversResponse_Driver) ProtoMessage() {}

func (x *GetDriversResponse_Driver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriversResponse_Driver.ProtoReflect.Descriptor instead.
func (*GetDriversResponse_Driver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetDriversResponse_Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *GetDriversResponse_Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetBike() string {
	if x != nil {
		return x.Bike
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *GetDriversResponse_Driver) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type ChooseDriverResponse_Restaurant struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*ChooseDriverResponse_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Restaurant) Reset() {
	*x = ChooseDriverResponse_Restaurant{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Restaurant) ProtoMessage() {}

func (x *ChooseDriverResponse_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Restaurant.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ChooseDriverResponse_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ChooseDriverResponse_Restaurant) GetItems() []*ChooseDriverResponse_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type ChooseDriverResponse_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Item) Reset() {
	*x = ChooseDriverResponse_Item{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Item) ProtoMessage() {}

func (x *ChooseDriverResponse_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Item.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 1}
}

func (x *ChooseDriverResponse_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ChooseDriverResponse_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type ChooseDriverResponse_Driver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AverageRating float64                `protobuf:"fixed64,2,opt,name=average_rating,json=averageRating,proto3" json:"average_rating,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Bike          string                 `protobuf:"bytes,4,opt,name=bike,proto3" json:"bike,omitempty"`
	LicensePlate  string                 `protobuf:"bytes,5,opt,name=license_plate,json=licensePlate,proto3" json:"license_plate,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,6,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseDriverResponse_Driver) Reset() {
	*x = ChooseDriverResponse_Driver{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseDriverResponse_Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseDriverResponse_Driver) ProtoMessage() {}

func (x *ChooseDriverResponse_Driver) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseDriverResponse_Driver.ProtoReflect.Descriptor instead.
func (*ChooseDriverResponse_Driver) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8, 2}
}

func (x *ChooseDriverResponse_Driver) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetAverageRating() float64 {
	if x != nil {
		return x.AverageRating
	}
	return 0
}

func (x *ChooseDriverResponse_Driver) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetBike() string {
	if x != nil {
		return x.Bike
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetLicensePlate() string {
	if x != nil {
		return x.LicensePlate
	}
	return ""
}

func (x *ChooseDriverResponse_Driver) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

type DriverGetPendingOrdersResponse_Order struct {
	state               protoimpl.MessageState                             `protogen:"open.v1"`
	Id                  string                                             `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Restaurants         []*DriverGetPendingOrdersResponse_Order_Restaurant `protobuf:"bytes,2,rep,name=restaurants,proto3" json:"restaurants,omitempty"`
	DeliveryAddress     string                                             `protobuf:"bytes,3,opt,name=delivery_address,json=deliveryAddress,proto3" json:"delivery_address,omitempty"`
	CustomerPhoneNumber string                                             `protobuf:"bytes,4,opt,name=customer_phone_number,json=customerPhoneNumber,proto3" json:"customer_phone_number,omitempty"`
	OrderStatus         string                                             `protobuf:"bytes,5,opt,name=order_status,json=orderStatus,proto3" json:"order_status,omitempty"`
	DeliveryFee         int64                                              `protobuf:"varint,6,opt,name=delivery_fee,json=deliveryFee,proto3" json:"delivery_fee,omitempty"`
	TotalFee            int64                                              `protobuf:"varint,7,opt,name=total_fee,json=totalFee,proto3" json:"total_fee,omitempty"`
	PaymentLink         string                                             `protobuf:"bytes,8,opt,name=payment_link,json=paymentLink,proto3" json:"payment_link,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order) Reset() {
	*x = DriverGetPendingOrdersResponse_Order{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0}
}

func (x *DriverGetPendingOrdersResponse_Order) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetRestaurants() []*DriverGetPendingOrdersResponse_Order_Restaurant {
	if x != nil {
		return x.Restaurants
	}
	return nil
}

func (x *DriverGetPendingOrdersResponse_Order) GetDeliveryAddress() string {
	if x != nil {
		return x.DeliveryAddress
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetCustomerPhoneNumber() string {
	if x != nil {
		return x.CustomerPhoneNumber
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetOrderStatus() string {
	if x != nil {
		return x.OrderStatus
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order) GetDeliveryFee() int64 {
	if x != nil {
		return x.DeliveryFee
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order) GetTotalFee() int64 {
	if x != nil {
		return x.TotalFee
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order) GetPaymentLink() string {
	if x != nil {
		return x.PaymentLink
	}
	return ""
}

type DriverGetPendingOrdersResponse_Order_Restaurant struct {
	state         protoimpl.MessageState                       `protogen:"open.v1"`
	Id            string                                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                                       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Address       string                                       `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Items         []*DriverGetPendingOrdersResponse_Order_Item `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) Reset() {
	*x = DriverGetPendingOrdersResponse_Order_Restaurant{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order_Restaurant) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order_Restaurant.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order_Restaurant) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0, 0}
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Restaurant) GetItems() []*DriverGetPendingOrdersResponse_Order_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

type DriverGetPendingOrdersResponse_Order_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverGetPendingOrdersResponse_Order_Item) Reset() {
	*x = DriverGetPendingOrdersResponse_Order_Item{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverGetPendingOrdersResponse_Order_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverGetPendingOrdersResponse_Order_Item) ProtoMessage() {}

func (x *DriverGetPendingOrdersResponse_Order_Item) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverGetPendingOrdersResponse_Order_Item.ProtoReflect.Descriptor instead.
func (*DriverGetPendingOrdersResponse_Order_Item) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10, 0, 1}
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *DriverGetPendingOrdersResponse_Order_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x02pb\x1a\x1bgoogle/protobuf/empty.proto\"\xf5\x01\n" +
	"\x12CreateOrderRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"user_email\x18\x02 \x01(\tR\tuserEmail\x1a\xa6\x01\n" +
	"\aOrderIn\x12!\n" +
	"\fdelivery_fee\x18\x01 \x01(\x03R\vdeliveryFee\x12A\n" +
	"\bitems_in\x18\x02 \x03(\v2&.pb.CreateOrderRequest.OrderIn.ItemsInR\aitemsIn\x1a5\n" +
	"\aItemsIn\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x03R\bquantity\".\n" +
	"\x11GetDriversRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\"M\n" +
	"\x13ChooseDriverRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"F\n" +
	"\x11GiveRatingRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x16\n" +
	"\x06rating\x18\x02 \x01(\x03R\x06rating\"T\n" +
	"\x1aDriverApplyForOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"T\n" +
	"\x1aDriverCompleteOrderRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1b\n" +
	"\tdriver_id\x18\x02 \x01(\tR\bdriverId\"\xae\x04\n" +
	"\x13CreateOrderResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12D\n" +
	"\vrestaurants\x18\x02 \x03(\v2\".pb.CreateOrderResponse.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\x1a~\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x122\n" +
	"\x05items\x18\x04 \x03(\v2\x1c.pb.CreateOrderResponse.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\xff\x01\n" +
	"\x12GetDriversResponse\x127\n" +
	"\adrivers\x18\x01 \x03(\v2\x1d.pb.GetDriversResponse.DriverR\adrivers\x1a\xaf\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04bike\x18\x04 \x01(\tR\x04bike\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\"\x9c\x06\n" +
	"\x14ChooseDriverResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\vrestaurants\x18\x02 \x03(\v2#.pb.ChooseDriverResponse.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x127\n" +
	"\x06driver\x18\x06 \x01(\v2\x1f.pb.ChooseDriverResponse.DriverR\x06driver\x12!\n" +
	"\fdelivery_fee\x18\a \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\b \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\t \x01(\tR\vpaymentLink\x1a\x7f\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x123\n" +
	"\x05items\x18\x04 \x03(\v2\x1d.pb.ChooseDriverResponse.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\x1a\xaf\x01\n" +
	"\x06Driver\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0eaverage_rating\x18\x02 \x01(\x01R\raverageRating\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04bike\x18\x04 \x01(\tR\x04bike\x12#\n" +
	"\rlicense_plate\x18\x05 \x01(\tR\flicensePlate\x12!\n" +
	"\fphone_number\x18\x06 \x01(\tR\vphoneNumber\"\x14\n" +
	"\x12GiveRatingResponse\"\xa8\x05\n" +
	"\x1eDriverGetPendingOrdersResponse\x12@\n" +
	"\x06orders\x18\x01 \x03(\v2(.pb.DriverGetPendingOrdersResponse.OrderR\x06orders\x1a\xc3\x04\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12U\n" +
	"\vrestaurants\x18\x02 \x03(\v23.pb.DriverGetPendingOrdersResponse.Order.RestaurantR\vrestaurants\x12)\n" +
	"\x10delivery_address\x18\x03 \x01(\tR\x0fdeliveryAddress\x122\n" +
	"\x15customer_phone_number\x18\x04 \x01(\tR\x13customerPhoneNumber\x12!\n" +
	"\forder_status\x18\x05 \x01(\tR\vorderStatus\x12!\n" +
	"\fdelivery_fee\x18\x06 \x01(\x03R\vdeliveryFee\x12\x1b\n" +
	"\ttotal_fee\x18\a \x01(\x03R\btotalFee\x12!\n" +
	"\fpayment_link\x18\b \x01(\tR\vpaymentLink\x1a\x8f\x01\n" +
	"\n" +
	"Restaurant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12C\n" +
	"\x05items\x18\x04 \x03(\v2-.pb.DriverGetPendingOrdersResponse.Order.ItemR\x05items\x1a\\\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x03R\bquantity\"\x1d\n" +
	"\x1bDriverApplyForOrderResponse\"\x1d\n" +
	"\x1bDriverCompleteOrderResponse2\x91\x04\n" +
	"\fOrderService\x12>\n" +
	"\vCreateOrder\x12\x16.pb.CreateOrderRequest\x1a\x17.pb.CreateOrderResponse\x12;\n" +
	"\n" +
	"GetDrivers\x12\x15.pb.GetDriversRequest\x1a\x16.pb.GetDriversResponse\x12A\n" +
	"\fChooseDriver\x12\x17.pb.ChooseDriverRequest\x1a\x18.pb.ChooseDriverResponse\x12;\n" +
	"\n" +
	"GiveRating\x12\x15.pb.GiveRatingRequest\x1a\x16.pb.GiveRatingResponse\x12T\n" +
	"\x16DriverGetPendingOrders\x12\x16.google.protobuf.Empty\x1a\".pb.DriverGetPendingOrdersResponse\x12V\n" +
	"\x13DriverApplyForOrder\x12\x1e.pb.DriverApplyForOrderRequest\x1a\x1f.pb.DriverApplyForOrderResponse\x12V\n" +
	"\x13DriverCompleteOrder\x12\x1e.pb.DriverCompleteOrderRequest\x1a\x1f.pb.DriverCompleteOrderResponseB5Z3github.com/airlangga-hub/food-delivery-app/order/pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_order_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),                              // 0: pb.CreateOrderRequest
	(*GetDriversRequest)(nil),                               // 1: pb.GetDriversRequest
	(*ChooseDriverRequest)(nil),                             // 2: pb.ChooseDriverRequest
	(*GiveRatingRequest)(nil),                               // 3: pb.GiveRatingRequest
	(*DriverApplyForOrderRequest)(nil),                      // 4: pb.DriverApplyForOrderRequest
	(*DriverCompleteOrderRequest)(nil),                      // 5: pb.DriverCompleteOrderRequest
	(*CreateOrderResponse)(nil),                             // 6: pb.CreateOrderResponse
	(*GetDriversResponse)(nil),                              // 7: pb.GetDriversResponse
	(*ChooseDriverResponse)(nil),                            // 8: pb.ChooseDriverResponse
	(*GiveRatingResponse)(nil),                              // 9: pb.GiveRatingResponse
	(*DriverGetPendingOrdersResponse)(nil),                  // 10: pb.DriverGetPendingOrdersResponse
	(*DriverApplyForOrderResponse)(nil),                     // 11: pb.DriverApplyForOrderResponse
	(*DriverCompleteOrderResponse)(nil),                     // 12: pb.DriverCompleteOrderResponse
	(*CreateOrderRequest_OrderIn)(nil),                      // 13: pb.CreateOrderRequest.OrderIn
	(*CreateOrderRequest_OrderIn_ItemsIn)(nil),              // 14: pb.CreateOrderRequest.OrderIn.ItemsIn
	(*CreateOrderResponse_Restaurant)(nil),                  // 15: pb.CreateOrderResponse.Restaurant
	(*CreateOrderResponse_Item)(nil),                        // 16: pb.CreateOrderResponse.Item
	(*GetDriversResponse_Driver)(nil),                       // 17: pb.GetDriversResponse.Driver
	(*ChooseDriverResponse_Restaurant)(nil),                 // 18: pb.ChooseDriverResponse.Restaurant
	(*ChooseDriverResponse_Item)(nil),                       // 19: pb.ChooseDriverResponse.Item
	(*ChooseDriverResponse_Driver)(nil),                     // 20: pb.ChooseDriverResponse.Driver
	(*DriverGetPendingOrdersResponse_Order)(nil),            // 21: pb.DriverGetPendingOrdersResponse.Order
	(*DriverGetPendingOrdersResponse_Order_Restaurant)(nil), // 22: pb.DriverGetPendingOrdersResponse.Order.Restaurant
	(*DriverGetPendingOrdersResponse_Order_Item)(nil),       // 23: pb.DriverGetPendingOrdersResponse.Order.Item
	(*emptypb.Empty)(nil),                                   // 24: google.protobuf.Empty
}
var file_order_proto_depIdxs = []int32{
	15, // 0: pb.CreateOrderResponse.restaurants:type_name -> pb.CreateOrderResponse.Restaurant
	17, // 1: pb.GetDriversResponse.drivers:type_name -> pb.GetDriversResponse.Driver
	18, // 2: pb.ChooseDriverResponse.restaurants:type_name -> pb.ChooseDriverResponse.Restaurant
	20, // 3: pb.ChooseDriverResponse.driver:type_name -> pb.ChooseDriverResponse.Driver
	21, // 4: pb.DriverGetPendingOrdersResponse.orders:type_name -> pb.DriverGetPendingOrdersResponse.Order
	14, // 5: pb.CreateOrderRequest.OrderIn.items_in:type_name -> pb.CreateOrderRequest.OrderIn.ItemsIn
	16, // 6: pb.CreateOrderResponse.Restaurant.items:type_name -> pb.CreateOrderResponse.Item
	19, // 7: pb.ChooseDriverResponse.Restaurant.items:type_name -> pb.ChooseDriverResponse.Item
	22, // 8: pb.DriverGetPendingOrdersResponse.Order.restaurants:type_name -> pb.DriverGetPendingOrdersResponse.Order.Restaurant
	23, // 9: pb.DriverGetPendingOrdersResponse.Order.Restaurant.items:type_name -> pb.DriverGetPendingOrdersResponse.Order.Item
	0,  // 10: pb.OrderService.CreateOrder:input_type -> pb.CreateOrderRequest
	1,  // 11: pb.OrderService.GetDrivers:input_type -> pb.GetDriversRequest
	2,  // 12: pb.OrderService.ChooseDriver:input_type -> pb.ChooseDriverRequest
	3,  // 13: pb.OrderService.GiveRating:input_type -> pb.GiveRatingRequest
	24, // 14: pb.OrderService.DriverGetPendingOrders:input_type -> google.protobuf.Empty
	4,  // 15: pb.OrderService.DriverApplyForOrder:input_type -> pb.DriverApplyForOrderRequest
	5,  // 16: pb.OrderService.DriverCompleteOrder:input_type -> pb.DriverCompleteOrderRequest
	6,  // 17: pb.OrderService.CreateOrder:output_type -> pb.CreateOrderResponse
	7,  // 18: pb.OrderService.GetDrivers:output_type -> pb.GetDriversResponse
	8,  // 19: pb.OrderService.ChooseDriver:output_type -> pb.ChooseDriverResponse
	9,  // 20: pb.OrderService.GiveRating:output_type -> pb.GiveRatingResponse
	10, // 21: pb.OrderService.DriverGetPendingOrders:output_type -> pb.DriverGetPendingOrdersResponse
	11, // 22: pb.OrderService.DriverApplyForOrder:output_type -> pb.DriverApplyForOrderResponse
	12, // 23: pb.OrderService.DriverCompleteOrder:output_type -> pb.DriverCompleteOrderResponse
	17, // [17:24] is the sub-list for method output_type
	10, // [10:17] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
